# =============================================================================
# variables.tf — input declarations
# =============================================================================
#
# Sandbox values committed in terraform.tfvars. No secret values — the
# master password is generated by random_password (see secrets.tf).

# ----- Project identity -----

variable "aws_region" {
  description = "AWS region. Must match the region the existing VPC lives in."
  type        = string
  default     = "us-east-1"
}

variable "name_prefix" {
  description = "Prefix for AWS resource names (matches the rest of the project)."
  type        = string
  default     = "sbx"
}

variable "owner_tag" {
  description = "Free-text owner tag attached to every resource (default_tags)."
  type        = string
  default     = "dkeeno"
}

# ----- Network discovery (data-source-driven) -----
#
# The stack reuses the existing project VPC instead of creating its own.
# Discovery is by tag name; if the cluster-iac stack is renamed/destroyed,
# update these values to match the new tags.

variable "vpc_name_tag" {
  description = "Name tag of the existing VPC the RDS instance should land in. Looked up via data.aws_vpc."
  type        = string
  default     = "sbx-vpc"
}

variable "private_subnet_name_pattern" {
  description = "Name-tag wildcard for the private subnets RDS should use (one per AZ). Actual sbx-cluster-iac uses 'sbx-prv-*' — the matching default is sbx-prv-*."
  type        = string
  default     = "sbx-prv-*"
}

variable "bastion_security_group_name" {
  description = "Name of the bastion's security group, granted ingress to the RDS instance for psql access via SSM."
  type        = string
  default     = "sbx-bastion-sg"
}

variable "additional_ingress_cidrs" {
  description = "Optional extra CIDR blocks allowed inbound on 5432 (e.g. your laptop's public IP/32 for direct seeding). Empty list = bastion-only."
  type        = list(string)
  default     = []
}

# ----- RDS instance sizing -----

variable "db_instance_class" {
  description = "RDS instance class. db.t4g.micro is the smallest Graviton size — enough for sandbox. ~$13/mo."
  type        = string
  default     = "db.t4g.micro"
}

variable "db_engine_version" {
  description = "PostgreSQL major.minor version. 16.x is the current LTS line."
  type        = string
  default     = "16.4"
}

variable "db_allocated_storage_gb" {
  description = "Initial storage. 20 GB is the gp3 minimum and plenty for a fictional enterprise dataset."
  type        = number
  default     = 20
}

variable "db_storage_type" {
  description = "Storage type. gp3 = baseline 3000 IOPS, no provisioning needed."
  type        = string
  default     = "gp3"
}

variable "db_name" {
  description = "Initial database name created at instance launch. Schemas (hr/sales/finance/audit) live INSIDE this database."
  type        = string
  default     = "enterprise_corp"
}

variable "db_master_username" {
  description = "Master account username. Avoid 'admin' / 'root' (RDS reserved). 'postgres' is fine."
  type        = string
  default     = "dbadmin"
}

variable "db_backup_retention_days" {
  description = "Daily backup retention. 1 day is the sandbox minimum that still lets you point-in-time-restore."
  type        = number
  default     = 1
}

variable "db_publicly_accessible" {
  description = "Whether RDS is reachable from the public internet (still gated by SG). Sandbox default: false (bastion-only access). Flip to true ONLY when you need to seed from your laptop and you've added your IP to additional_ingress_cidrs."
  type        = bool
  default     = false
}

variable "db_skip_final_snapshot" {
  description = "On terraform destroy, skip the final snapshot. Sandbox default: true (no point keeping snapshots for fictional data)."
  type        = bool
  default     = true
}

variable "db_deletion_protection" {
  description = "Block accidental terraform destroy. Sandbox default: false."
  type        = bool
  default     = false
}
